require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.
#
# Also compared to earlier versions of this generator, there are no longer any
# expectations of assigns and templates rendered. These features have been
# removed from Rails core in Rails 5, but can be added back in via the
# `rails-controller-testing` gem.

RSpec.describe GalleriesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Gallery. As you add validations to Gallery, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    attributes_for(:gallery)
  }

  let(:invalid_attributes) {
    attributes_for(:gallery, name: "")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # GalleriesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "returns a success response" do
      get :index, params: {}, session: valid_session
      expect(response).to be_success
    end
  end

  describe "GET #show" do
    let(:gallery) { create :gallery }

    it "returns a success response" do
      get :show, params: {id: gallery.to_param}, session: valid_session
      expect(response).to be_success
    end
  end

  describe "GET #new" do
    it "returns a success response" do
      get :new, params: {}, session: valid_session
      expect(response).to be_success
    end
  end

  describe "GET #edit" do
    let(:gallery) { create :gallery }

    it "returns a success response" do
      get :edit, params: {id: gallery.to_param}, session: valid_session
      expect(response).to be_success
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Gallery" do
        expect {
          post :create, params: {gallery: valid_attributes}, session: valid_session
        }.to change(Gallery, :count).by(1)
      end

      it "redirects to the created gallery" do
        post :create, params: {gallery: valid_attributes}, session: valid_session
        expect(response).to redirect_to(Gallery.last)
      end
    end

    context "with invalid params" do
      it "returns a success response (i.e. to display the 'new' template)" do
        post :create, params: {gallery: invalid_attributes}, session: valid_session
        expect(response).to be_success
      end
    end
  end

  describe "PUT #update" do
    let(:gallery) { create :gallery }

    context "with valid params" do
      let(:new_attributes) {
        attributes_for(:gallery, name: "New name")
      }

      it "updates the requested gallery" do
        put :update, params: {id: gallery.to_param, gallery: new_attributes}, session: valid_session
        gallery.reload
        expect(gallery.name).to eq "New name"
      end

      it "redirects to the gallery" do
        gallery = Gallery.create! valid_attributes
        put :update, params: {id: gallery.to_param, gallery: valid_attributes}, session: valid_session
        expect(response).to redirect_to(gallery)
      end
    end

    context "with invalid params" do
      it "returns a success response (i.e. to display the 'edit' template)" do
        put :update, params: {id: gallery.to_param, gallery: invalid_attributes}, session: valid_session
        expect(response).to be_success
      end
    end
  end

  describe "DELETE #destroy" do
    let!(:gallery) { create :gallery }

    it "destroys the requested gallery" do
      expect {
        delete :destroy, params: {id: gallery.to_param}, session: valid_session
      }.to change(Gallery, :count).by(-1)
    end

    it "redirects to the galleries list" do
      delete :destroy, params: {id: gallery.to_param}, session: valid_session
      expect(response).to redirect_to(galleries_url)
    end
  end

end
