require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.
#
# Also compared to earlier versions of this generator, there are no longer any
# expectations of assigns and templates rendered. These features have been
# removed from Rails core in Rails 5, but can be added back in via the
# `rails-controller-testing` gem.

RSpec.describe IntervalsController, type: :controller do
  let!(:user) { sign_in_as_user }

  # This should return the minimal set of attributes required to create a valid
  # Interval. As you add validations to Interval, be sure to
  # adjust the attributes here as well.
  let(:timeline) { create :timeline }

  let(:valid_attributes) {
    attributes_for(:interval, timeline: nil)
  }

  let(:invalid_attributes) {
    attributes_for(:interval, timeline: nil, title_da: "")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # IntervalsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "returns a success response" do
      get :index, params: { timeline_id: timeline.id }, session: valid_session
      expect(response).to be_success
    end
  end

  describe "GET #show" do
    let(:interval) { create :interval }

    it "returns a success response" do
      get :show, params: {id: interval.to_param}, session: valid_session
      expect(response).to be_success
    end
  end

  describe "GET #new" do
    it "returns a success response" do
      get :new, params: { timeline_id: timeline.id }, session: valid_session
      expect(response).to be_success
    end
  end

  describe "GET #edit" do
    let(:interval) { create :interval }

    it "returns a success response" do
      get :edit, params: {id: interval.to_param}, session: valid_session
      expect(response).to be_success
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Interval" do
        expect {
          post :create, params: {timeline_id: timeline.id, interval: valid_attributes}, session: valid_session
        }.to change(Interval, :count).by(1)
      end

      it "redirects to the created interval" do
        post :create, params: {timeline_id: timeline.id, interval: valid_attributes}, session: valid_session
        expect(response).to redirect_to(Interval.last)
      end
    end

    context "with invalid params" do
      it "returns a success response (i.e. to display the 'new' template)" do
        post :create, params: {timeline_id: timeline.id, interval: invalid_attributes}, session: valid_session
        expect(response).to be_success
      end
    end
  end

  describe "PUT #update" do
    let(:interval) { create :interval }

    context "with valid params" do
      let(:new_attributes) {
        { title_da: "New title" }
      }

      it "updates the requested interval" do
        put :update, params: {id: interval.to_param, interval: new_attributes}, session: valid_session
        interval.reload
        expect(interval.title_da).to eq "New title"
      end

      it "redirects to the interval" do
        put :update, params: {id: interval.to_param, interval: valid_attributes}, session: valid_session
        expect(response).to redirect_to(interval)
      end
    end

    context "with invalid params" do
      it "returns a success response (i.e. to display the 'edit' template)" do
        put :update, params: {id: interval.to_param, interval: invalid_attributes}, session: valid_session
        expect(response).to be_success
      end
    end
  end

  describe "DELETE #destroy" do
    let!(:interval) { create :interval, timeline: timeline }

    it "destroys the requested interval" do
      expect {
        delete :destroy, params: {id: interval.to_param}, session: valid_session
      }.to change(Interval, :count).by(-1)
    end

    it "redirects to the intervals list" do
      delete :destroy, params: {id: interval.to_param}, session: valid_session
      expect(response).to redirect_to(timeline)
    end
  end

end
