require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.
#
# Also compared to earlier versions of this generator, there are no longer any
# expectations of assigns and templates rendered. These features have been
# removed from Rails core in Rails 5, but can be added back in via the
# `rails-controller-testing` gem.

RSpec.describe QuizOptionsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # QuizOption. As you add validations to QuizOption, be sure to
  # adjust the attributes here as well.
  let(:quiz) { create :quiz }

  let(:valid_attributes) {
    attributes_for(:quiz_option)
  }

  let(:invalid_attributes) {
    attributes_for(:quiz_option, option_da: "")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # QuizOptionsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "returns a success response" do
      get :index, params: { quiz_id: quiz.to_param }, session: valid_session
      expect(response).to be_success
    end
  end

  describe "GET #show" do
    let(:quiz_option) { create :quiz_option }

    it "returns a success response" do
      get :show, params: {id: quiz_option.to_param}, session: valid_session
      expect(response).to be_success
    end
  end

  describe "GET #new" do
    it "returns a success response" do
      get :new, params: { quiz_id: quiz.to_param }, session: valid_session
      expect(response).to be_success
    end
  end

  describe "GET #edit" do
    let(:quiz_option) { create :quiz_option }

    it "returns a success response" do
      get :edit, params: {id: quiz_option.to_param}, session: valid_session
      expect(response).to be_success
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new QuizOption" do
        expect {
          post :create, params: {quiz_id: quiz.to_param, quiz_option: valid_attributes}, session: valid_session
        }.to change(QuizOption, :count).by(1)
      end

      it "redirects to the created quiz_option" do
        post :create, params: {quiz_id: quiz.to_param, quiz_option: valid_attributes}, session: valid_session
        expect(response).to redirect_to(QuizOption.last)
      end
    end

    context "with invalid params" do
      it "returns a success response (i.e. to display the 'new' template)" do
        post :create, params: {quiz_id: quiz.to_param, quiz_option: invalid_attributes}, session: valid_session
        expect(response).to be_success
      end
    end
  end

  describe "PUT #update" do
    let(:quiz_option) { create :quiz_option }

    context "with valid params" do
      let(:new_attributes) {
        { option_da: "New option" }
      }

      it "updates the requested quiz_option" do
        put :update, params: {id: quiz_option.to_param, quiz_option: new_attributes}, session: valid_session
        quiz_option.reload
        expect(quiz_option.option_da).to eq "New option"
      end

      it "redirects to the quiz_option" do
        put :update, params: {id: quiz_option.to_param, quiz_option: valid_attributes}, session: valid_session
        expect(response).to redirect_to(quiz_option)
      end
    end

    context "with invalid params" do
      it "returns a success response (i.e. to display the 'edit' template)" do
        put :update, params: {id: quiz_option.to_param, quiz_option: invalid_attributes}, session: valid_session
        expect(response).to be_success
      end
    end
  end

  describe "DELETE #destroy" do
    let!(:quiz_option) { create :quiz_option, quiz: quiz }

    it "destroys the requested quiz_option" do
      expect {
        delete :destroy, params: {id: quiz_option.to_param}, session: valid_session
      }.to change(QuizOption, :count).by(-1)
    end

    it "redirects to the quiz_options list" do
      delete :destroy, params: {id: quiz_option.to_param}, session: valid_session
      expect(response).to redirect_to(quiz)
    end
  end

end
