require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.
#
# Also compared to earlier versions of this generator, there are no longer any
# expectations of assigns and templates rendered. These features have been
# removed from Rails core in Rails 5, but can be added back in via the
# `rails-controller-testing` gem.

RSpec.describe TimelinesController, type: :controller do
  let!(:user) { sign_in_as_user }

  # This should return the minimal set of attributes required to create a valid
  # Timeline. As you add validations to Timeline, be sure to
  # adjust the attributes here as well.
  let(:theme) { create :theme }

  let(:valid_attributes) {
    attributes_for(:timeline)
  }

  let(:invalid_attributes) {
    attributes_for(:timeline, title_da: "")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TimelinesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "returns a success response" do
      get :index, params: { theme_id: theme.to_param }, session: valid_session
      expect(response).to be_success
    end
  end

  describe "GET #show" do
    let(:timeline) { create :timeline, theme: theme }

    it "returns a success response" do
      get :show, params: {id: timeline.to_param}, session: valid_session
      expect(response).to be_success
    end
  end

  describe "GET #new" do
    it "returns a success response" do
      get :new, params: { theme_id: theme.to_param }, session: valid_session
      expect(response).to be_success
    end
  end

  describe "GET #edit" do
    let(:timeline) { create :timeline, theme: theme }

    it "returns a success response" do
      get :edit, params: {id: timeline.to_param}, session: valid_session
      expect(response).to be_success
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Timeline" do
        expect {
          post :create, params: { theme_id: theme.to_param, timeline: valid_attributes }, session: valid_session
        }.to change(Timeline, :count).by(1)
      end

      it "redirects to the created timeline" do
        post :create, params: { theme_id: theme.to_param, timeline: valid_attributes }, session: valid_session
        expect(response).to redirect_to(Timeline.last)
      end
    end

    context "with invalid params" do
      it "returns a success response (i.e. to display the 'new' template)" do
        post :create, params: { theme_id: theme.to_param, timeline: invalid_attributes }, session: valid_session
        expect(response).to be_success
      end
    end
  end

  describe "PUT #update" do
    let(:timeline) { create :timeline, theme: theme }

    context "with valid params" do
      let(:new_attributes) {
        { title_da: "New title" }
      }

      it "updates the requested timeline" do
        put :update, params: {id: timeline.to_param, timeline: new_attributes}, session: valid_session
        timeline.reload
        expect(timeline.title_da).to eq "New title"
      end

      it "redirects to the timeline" do
        put :update, params: {id: timeline.to_param, timeline: valid_attributes}, session: valid_session
        expect(response).to redirect_to(timeline)
      end
    end

    context "with invalid params" do
      it "returns a success response (i.e. to display the 'edit' template)" do
        put :update, params: {id: timeline.to_param, timeline: invalid_attributes}, session: valid_session
        expect(response).to be_success
      end
    end
  end

  describe "DELETE #destroy" do
    let!(:timeline) { create :timeline, theme: theme }

    it "destroys the requested timeline" do
      expect {
        delete :destroy, params: {id: timeline.to_param}, session: valid_session
      }.to change(Timeline, :count).by(-1)
    end

    it "redirects to the timelines list" do
      delete :destroy, params: {id: timeline.to_param}, session: valid_session
      expect(response).to redirect_to(theme)
    end
  end

end
