require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.
#
# Also compared to earlier versions of this generator, there are no longer any
# expectations of assigns and templates rendered. These features have been
# removed from Rails core in Rails 5, but can be added back in via the
# `rails-controller-testing` gem.

RSpec.describe VideosController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Video. As you add validations to Video, be sure to
  # adjust the attributes here as well.
  let(:video_gallery) { create :video_gallery }

  let(:valid_attributes) {
    attributes_for(:video)
  }

  let(:invalid_attributes) {
    attributes_for(:video, title_da: "")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # VideosController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "returns a success response" do
      get :index, params: { video_gallery_id: video_gallery.to_param }, session: valid_session
      expect(response).to be_success
    end
  end

  describe "GET #show" do
    let(:video) { create :video }

    it "returns a success response" do
      get :show, params: {id: video.to_param}, session: valid_session
      expect(response).to be_success
    end
  end

  describe "GET #new" do
    it "returns a success response" do
      get :new, params: { video_gallery_id: video_gallery.to_param }, session: valid_session
      expect(response).to be_success
    end
  end

  describe "GET #edit" do
    let(:video) { create :video }

    it "returns a success response" do
      get :edit, params: {id: video.to_param}, session: valid_session
      expect(response).to be_success
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Video" do
        expect {
          post :create, params: { video_gallery_id: video_gallery.to_param, video: valid_attributes}, session: valid_session
        }.to change(Video, :count).by(1)
      end

      it "redirects to the created video" do
        post :create, params: { video_gallery_id: video_gallery.to_param, video: valid_attributes}, session: valid_session
        expect(response).to redirect_to(Video.last)
      end
    end

    context "with invalid params" do
      it "returns a success response (i.e. to display the 'new' template)" do
        post :create, params: { video_gallery_id: video_gallery.to_param, video: invalid_attributes}, session: valid_session
        expect(response).to be_success
      end
    end
  end

  describe "PUT #update" do
    let(:video) { create :video }

    context "with valid params" do
      let(:new_attributes) {
        { title_da: "New title" }
      }

      it "updates the requested video" do
        put :update, params: {id: video.to_param, video: new_attributes}, session: valid_session
        video.reload
        expect(video.title_da).to eq "New title"
      end

      it "redirects to the video" do
        put :update, params: {id: video.to_param, video: valid_attributes}, session: valid_session
        expect(response).to redirect_to(video)
      end
    end

    context "with invalid params" do
      it "returns a success response (i.e. to display the 'edit' template)" do
        put :update, params: {id: video.to_param, video: invalid_attributes}, session: valid_session
        expect(response).to be_success
      end
    end
  end

  describe "DELETE #destroy" do
    let!(:video) { create :video }

    it "destroys the requested video" do
      expect {
        delete :destroy, params: {id: video.to_param}, session: valid_session
      }.to change(Video, :count).by(-1)
    end

    it "redirects to the videos list" do
      delete :destroy, params: {id: video.to_param}, session: valid_session
      expect(response).to redirect_to(video_gallery_url(video.video_gallery))
    end
  end

end
